### ISSUE TITLE
Фичи

### ISSUE THREAD

**Issue by bropines** [AntonRls/Manga-Translator#1]
Так как ты русский, писать буду на русском

1. Изменение шрифта на свой
2. Добавление сторонних служб перевода
3. Импорт всей папки манги(с отображением страниц)
4. Темная тема
5. Распознавание в некоторых местах хромает
6. Ну заапдейти ты хоть чтонибудь)

Если вдруг нужна помощь, то t.me/bropines

**Comment by AntonRls** [comment]
Спасибо за предложение. Скоро реализую

**Comment by bropines** [comment]
Ну и как вишенку на торте. Если умеешь в GUI, то я могу задизайнить тебе дизайн (rus, eng). Будет красиво и все функции учту)

**Comment by AntonRls** [comment]
Ага, в винформах пойду дизайн делать, не, спасибо)

**Comment by bropines** [comment]
> Ага, в винформах пойду дизайн делать, не, спасибо)

Понял. Сам если что потом на UWP ченить состряпаю

**Comment by bropines** [comment]
А можно юзать tesseract OCR? Плотить (ну или пиратить) лень. Или другой но бесплатный движок)
