### ISSUE TITLE
Save function isn't working.

### ISSUE THREAD

**Issue by isseisuman** [AntonRls/Manga-Translator#2]
I tried with multiple images on a folder, have set up output folder too, but after saving, nothing is on the output folder. Then tried with "Open one picture" button, same result.

**Comment by AntonRls** [comment]
How do you specify the path to the output folder? For normal operation, I advise you to specify the absolute path

**Comment by AntonRls** [comment]
https://user-images.githubusercontent.com/74132592/182089988-e75ad05c-dae1-40ea-ba63-22b4ed134a06.mp4

The save function works in my case

**Comment by isseisuman** [comment]
I gave it a full output path. But for some reason it wasn't saving. Tried it again and it is working. 

Thanks for the fast reply.
