### ISSUE TITLE
Translator dose not Work

### ISSUE THREAD

**Issue by 72Joe72** [AntonRls/Manga-Translator#3]
The Translator dosent work for me.
I use the 'test Picture' and leave all settings 
![image](https://user-images.githubusercontent.com/43684517/208958474-fc8a81d0-cf2e-48f1-89d8-502e14124ec2.png)

**Comment by 72Joe72** [comment]
If i deaktivate translate then i get the normal japenees letters 
![image](https://user-images.githubusercontent.com/43684517/208958881-608a1a8c-82ee-4a2d-8f39-750d707f8f19.png)

**Comment by AntonRls** [comment]
Hello! Perhaps something has changed in the Google Translate API. I will deal with this problem later. Thanks for the feedback

**Comment by AntonRls** [comment]
I fixed this in the new release
