### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by MoonDragon-MD** [AntonRls/Manga-Translator#4]
Hi, I found your program interesting.

I wanted to know if it is possible to set both input and output language? I would be interested in French input and Italian output.

Also, a setting to use tesseract without the additional API would be interesting.

For translation what is used? Is it possible to have an offline translation? (maybe you could use argosopentech you can find it here on Github)

Thank you

**Comment by AntonRls** [comment]
Hello, unfortunately, the translation is only available from Japanese.  The translation is done by a neural network, and the weights for each language weigh a lot, and they need to be downloaded separately.

You can download the project sources, install the language you need via Nuget, and compile the project

**Comment by MoonDragon-MD** [comment]
Hi, thank you for responding! 

Maybe one day I will try to compile the sources.

goodbye
