### ISSUE TITLE
Free OCR and other suggestion

### ISSUE THREAD

**Issue by dhana-exe** [AntonRls/Manga-Translator#5]
Hello, Ummm before i asking i would thanks to you for making this amazing software....
thanks alot

umm issue from me is getting key for the OCR... how about on future you can use offline OCR that "present" on github?
alot of people had this type of OCR
and they seems works perfect for japanese character... so all you need to do is just use it or upgrade it

i think if we depend to ocr from paid source it's will be waste money on future

and for translation, i really sure maybe if you can add "CHATGPT"
they free as far as i know, and the more important they had more accurate translation, compared to booth google, deeptl and bing
maybe that's my suggestion and feedback about your app

btw
thanks alot for making this possible
you're great

**Comment by AntonRls** [comment]
Thanks for the good idea! In the near future I will consider the available implementation options, and I will try to develop

**Comment by dhana-exe** [comment]
> Thanks for the good idea! In the near future I will consider the available implementation options, and I will try to develop

thanks :>

**Comment by AntonRls** [comment]
I checked Tesseract and it doesn't recognize the text normally (attached a screenshot). I will be glad if you attach links to repositories where Japanese text recognition works properly.

As for the ChatGPT integration, I added this in the new release
![2023-09-12_18-46-14](https://github.com/AntonRls/Manga-Translator/assets/74132592/141f5975-158b-44dd-9206-a6b173c28ff6)
