### ISSUE TITLE
Add support for Google OCR and Deepl

### ISSUE THREAD

**Issue by Cloudstrifeff7** [AntonRls/Manga-Translator#6]
Can support for Google OCR and Deepl be added? Thanks!

**Comment by AntonRls** [comment]
Hello, both options are paid.  There is no point in implementing them.  I will be glad if you offer alternative free options

**Comment by Cloudstrifeff7** [comment]
There is free deepl api for 500.000 characters every month. 
Google charges money for using their services after you hit a certain limit (there is reset for this limit every month). I’ve never actually had to pay anything.

I am using this: https://github.com/SethRobinson/UGT

I have never spent any money and I read a lot of JRPGs in English or Japanese to translate them into my own language.

**Comment by AntonRls** [comment]
Okay, I'll implement this soon.  Thank you

**Comment by AntonRls** [comment]
I have added DeepL support. Unfortunately, Google OCR can't be added
