### ISSUE TITLE
WinOCR

### ISSUE THREAD

**Issue by bropines** [AntonRls/Manga-Translator#7]
В системе винды будь то 10 или 11 есть встроенный ocr движок. Так как IronOCR платный и вообще не ахти для манги, можно же добавить бесплатный и [встроенный](https://learn.microsoft.com/en-us/uwp/api/windows.media.ocr?view=winrt-22621). Ну или добавить питоновскую версию [MangaOCR](https://github.com/kha-white/manga-ocr?tab=readme-ov-file)

**Comment by AntonRls** [comment]
На текущий момент IronOCR идеально обрабатывает текст в манге. Про WinOCR, если честно, слышу впервые, обязательно рассмотрю

**Comment by bropines** [comment]
> На текущий момент IronOCR идеально обрабатывает текст в манге. Про WinOCR, если честно, слышу впервые, обязательно рассмотрю

Тут прикол просто, у нас же есть BallonTranslator и его окр движки, и по моему сравнению прям угашеный задний фон он чуть лучше обрабатывает. А так да, я тестил обоих, и iron просто платный 0-0

**Comment by AntonRls** [comment]
К сожалению, winocr не получится добавить
